# Generated by Django 5.0.3 on 2024-04-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=124, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("year", models.DateTimeField(blank=True, null=True)),
                ("year_disband", models.DateTimeField(blank=True, null=True)),
                ("formed_in", models.CharField(blank=True, max_length=82, null=True)),
                ("about", models.TextField(blank=True, max_length=4800, null=True)),
                (
                    "pic",
                    models.FileField(default="artists/Cover.jpg", upload_to="artists/"),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=124)),
                ("year", models.DateTimeField(blank=True, null=True)),
                ("cover", models.FileField(blank=True, null=True, upload_to="covers/")),
                ("about", models.TextField(blank=True, max_length=4800, null=True)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=124)),
                ("year", models.DateTimeField(blank=True, null=True)),
                ("about", models.TextField(blank=True, max_length=2800, null=True)),
                ("listen_count", models.IntegerField(default=1)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scrobble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.song"
                    ),
                ),
            ],
        ),
    ]
